name: Trigger auto deployment for component2222

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/component2222-AutoDeployTrigger-f5d03b89-d143-475d-8c6a-99a502079b7c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.COMPONENT2222_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COMPONENT2222_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COMPONENT2222_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryqkqldiou3y57m.azurecr.io
          registryUsername: ${{ secrets.COMPONENT2222_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COMPONENT2222_REGISTRY_PASSWORD }}
          containerAppName: component2222
          resourceGroup: githubactiontestapppython99ef
          imageToBuild: containerregistryqkqldiou3y57m.azurecr.io/component2222:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


