name: Trigger auto deployment for container-app-n3kqipqmydcbo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/container-app-n3kqipqmydcbo-AutoDeployTrigger-af7d2781-1434-404d-8065-db6d1bb1e499.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPN3KQIPQMYDCBO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPN3KQIPQMYDCBO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPN3KQIPQMYDCBO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPN3KQIPQMYDCBO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPN3KQIPQMYDCBO_REGISTRY_PASSWORD }}
          containerAppName: container-app-n3kqipqmydcbo
          resourceGroup: todonodejspgsqlgoogleauth936fa186
          imageToBuild: default/container-app-n3kqipqmydcbo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


