name: Trigger auto deployment for next13onswa85e2a317

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/next13onswa85e2a317-AutoDeployTrigger-c3771d44-3091-463a-911f-8d1c27873126.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.NEXT13ONSWA85E2A317_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NEXT13ONSWA85E2A317_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NEXT13ONSWA85E2A317_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.NEXT13ONSWA85E2A317_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NEXT13ONSWA85E2A317_REGISTRY_PASSWORD }}
          containerAppName: next13onswa85e2a317
          resourceGroup: next13onswa85e2
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


